// <auto-generated />
using System;
using DSSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSSystem.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20250407120519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("LoginStruct", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.ToTable("LoginStruct");

                    b.HasData(
                        new
                        {
                            Username = "Wilson",
                            DateTime = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "1234",
                            Success = true
                        },
                        new
                        {
                            Username = "Isak",
                            DateTime = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "1234",
                            Success = true
                        },
                        new
                        {
                            Username = "Burn",
                            DateTime = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "1234",
                            Success = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
